# Generated by Django 5.0.2 on 2024-02-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publication',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='translation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='preview',
            field=models.ImageField(blank=True, upload_to='category/preview'),
        ),
    ]
