version: '3.9'
services:

  nginx:
    build: ./nginx
    links:
      - frontend
    depends_on:
      - frontend
    ports:
      - "80:80"
      - "443:443"    
    networks:
      - prod
  
  frontend:
    container_name: frontend
    build: .
    networks:
      - prod

networks:
  prod:
    external: true