# Generated by Django 5.0.1 on 2024-01-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('preview', models.ImageField(blank=True, upload_to='post/preview')),
            ],
        ),
    ]
